### ISSUE TITLE
Relative path is absolute in examples

### ISSUE THREAD

**Issue by stbain** [mikosullivan/xeme#2]
The examples have an absolute path that will likely need to converted to a relative path.

Here is an example link to the line in the `return.rb` file:
https://github.com/mikosullivan/xeme/blob/0d8958b33c5d0d23dde24cc3466396c4442f706b/documentation/examples/object/messages/return.rb#LL2C15-L2C15

**Comment by stbain** [comment]
Note: This issue is replicated in multiple files in the examples directory.

**Comment by mikosullivan** [comment]
Those lines shouldn't be there in the first place. I'll remove them and upload a new version. Thanks for the feedback.

**Comment by mikosullivan** [comment]
Resolved in overhaul of gem.
